apiVersion: v1
kind: Namespace
metadata:
  name: registry-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: registry
  name: registry
  namespace: registry-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      volumes:
      - name: data-dir
        hostPath:
          path: /opt/lab/registry/data
      - name: config-dir
        hostPath:
          path: /opt/lab/registry/config
      - name: config-file
        hostPath:
          path: /opt/lab/registry/config.yaml
      containers:
      - image: distribution/registry:2.1
        name: distribution
        volumeMounts:
        - name: data-dir
          mountPath: /var/lib/registry
        - name: config-dir
          mountPath: /opt/config
        - name: config-file
          mountPath: /etc/docker/registry/config.yml
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: registry
  name: registry
  namespace: registry-system
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: registry
status:
  loadBalancer: {}
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: registry
#  namespace: registry-system
#  annotations:
#    traefik.ingress.kubernetes.io/router.entrypoints: websecure
#spec:
#  rules:
#  - host: registry.hgalal.az
#    http:
#      paths:
#      - backend:
#          service:
#            name: registry
#            port:
#              number: 5000
#        path: /
#        pathType: Prefix
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: registry
  namespace: registry-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`registry.hgalal.az`)
    services:
    - name: registry
      port: 5000
      weight: 3
  tls:
    passthrough: true
